# .pre-commit-config.yaml
repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      # modifies files → only at local pre-commit
      - id: nbstripout
        stages: [pre-commit]
        files: \.ipynb$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # read-only checks → run locally and in CI
      - id: detect-private-key
        stages: [pre-commit, manual]
      - id: check-added-large-files
        args: ["--maxkb=1000"]
        stages: [pre-commit, manual]
      - id: end-of-file-fixer
        stages: [pre-commit]     # modifies files, so not in CI
      - id: trailing-whitespace
        stages: [pre-commit]     # modifies files, so not in CI
      - id: check-yaml
        stages: [pre-commit, manual]
      - id: check-json
        stages: [pre-commit, manual]

# Don’t scan generated stuff
exclude: |
  (?x)
  ^docs/_build/|
  ^dist/|
  ^site/|
  \.sigstore\.json$|
  \.intoto\.jsonl$
