# CI will run the "manual" stage. Hooks that MODIFY files run only at "commit" (local),
# so CI won't fail because it can't commit the changes.
repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        stages: [commit]  # modify locally; skipped in CI (manual)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: detect-private-key
        stages: [commit, manual]
      - id: check-added-large-files
        args: ["--maxkb=1000"]
        stages: [commit, manual]
      - id: end-of-file-fixer
        stages: [commit]  # modify locally; skipped in CI
      - id: trailing-whitespace
        stages: [commit]  # modify locally; skipped in CI
      - id: check-yaml
        stages: [commit, manual]
      - id: check-json
        stages: [commit, manual]
