name: Build & Deploy Jupyter Book

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIT_HTTP_LOW_SPEED_LIMIT: "1000"
      GIT_HTTP_LOW_SPEED_TIME: "60"

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout (git)
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ github.sha }}
          fetch-depth: 1

      - name: Retry checkout (full fetch)
        if: failure()
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0

      - name: Fallback download source archive
        if: failure()
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euxo pipefail
          URL="https://api.github.com/repos/${{ github.repository }}/tarball/${{ github.sha }}"
          curl -sSL --retry 5 --retry-delay 5 \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "$URL" -o src.tgz
          mkdir -p "$GITHUB_WORKSPACE"
          tar -xzf src.tgz --strip-components=1 -C "$GITHUB_WORKSPACE"
          git init
          git config user.email "actions@github.com"
          git config user.name "github-actions"
          git add -A
          git commit -m "Archive checkout (fallback)"

      - name: Install pipx + jupyter-book (pinned)
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y pipx
          pipx ensurepath
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          pipx install jupyter-book==1.0.4.post1

      - name: Build book
        run: jupyter-book build docs

      - name: Configure Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4
        with:
          path: docs/_build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
