name: CI (tests)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: {}   # to manually trigger the workflow

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PIP_REQUIRE_HASHES: "1"   # enforce hash-checked installs

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.11"
          cache: "pip"
