name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: "3.12"

      - name: Install tooling
        run: |
          python -m pip install -U pip
          python -m pip install pre-commit jupyter-book

      # Run only "manual" stage hooks in CI.
      # Hooks that modify files (EOF fixer, trailing whitespace, nbstripout) are limited to the "commit" stage,
      # so they won't run here and CI won't fail due to uncommitted changes.
      - name: Run pre-commit (CI-safe)
        run: |
          pre-commit install-hooks
          pre-commit run --all-files --hook-stage manual --show-diff-on-failure

      - name: Validate Jupyter Book builds
        run: |
          jupyter-book build --keep-going docs
