name: Link Check

on:
  schedule: [{ cron: "23 3 * * *" }]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5 (pinned)
      - name: Check links in docs
        uses: lycheeverse/lychee-action@885c65f3dc543b57c898c8099f4e08c8afd178a2 # v2.6.1 commit
        with:
          args: --no-progress --require-https --max-concurrency 8 docs
